server:
  port: 8070
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/tickets
    username: program
    password: test
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
springdoc:
  swagger-ui:
    path: /api/v1/docs
